/* eslint-disable max-lines */
/* eslint-disable max-len */

export const mockFetchData = {
  count: 1698,
  page: 1,
  totalPages: 17,
  nextPage: 2,
  previousPage: 0,
  showingFrom: 1,
  showingTo: 100,
  items: [
    {
      id: 37931,
      tipo: 'Notícia',
      titulo: 'Servidores do IBGE no RS se mobilizam para ajudar desabrigados nas enchentes',
      introducao: 'Servidores da Superintendência RS e da Agência de Lajeado levaram solidariedade e mantimentos às vítimas das enchentes que atingiram o Vale do Taquari - Foto - Acervo IBGE Na última semana, servidores do IBGE no Rio Grande do Sul se mobilizaram para...',
      data_publicacao: '19/09/2023 10:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_09\\/Doaes_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_09\\/Doaes_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37931-servidores-do-ibge-no-rs-se-mobilizam-para-ajudar-desabrigados-nas-enchentes.html',
    },
    {
      id: 37917,
      tipo: 'Notícia',
      titulo: 'IBGE: mais de 180 mil candidatos farão provas neste domingo, em todo o país',
      introducao: 'Processos seletivos receberam mais de 180 mil inscrições - Foto: Acervo IBGE A partir das 9h do próximo domingo, começam em todo o país as provas para Agente de Pesquisas e Mapeamento (APM) e Supervisor de Coleta e Qualidade (SCQ) do IBGE. Serão 181.610...',
      data_publicacao: '15/09/2023 14:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_09\\/PSS-APM_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_09\\/PSS-APM_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37917-ibge-mais-de-180-mil-candidatos-farao-provas-neste-domingo-em-todo-o-pais.html',
    },
    {
      id: 37913,
      tipo: 'Notícia',
      titulo: 'Taxa de sindicalização cai a 9,2% em 2022, menor nível da série',
      introducao: 'Em 2022, menos de 10% dos trabalhadores eram sindicalizados, chegando ao menor contingente da série iniciada em 2012 - Foto: Rovena Rosa/Agência Brasil Em 2022, das 99,6 milhões de pessoas ocupadas, 9,2% (9,1 milhões de pessoas) eram associadas a...',
      data_publicacao: '15/09/2023 10:00:00',
      produto_id: 17270,
      produtos: '17270|Divulgação anual#pnadc3|pnad-continua|2511',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_09\\/PNAD-Sindical_THUMB_Rovena-Rosa-Agncia-Brasil.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_09\\/PNAD-Sindical_HOME_Rovena-Rosa-Agncia-Brasil.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '17270',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37913-taxa-de-sindicalizacao-cai-a-9-2-em-2022-menor-nivel-da-serie.html',
    },
    {
      id: 37908,
      tipo: 'Notícia',
      titulo: 'Volume de vendas no comércio tem alta de 0,7% em julho',
      introducao: 'Setor de artigos de uso pessoal e doméstico influenciou no resultado do comércio de julho - Foto: Alerrandre Barros/Agência IBGE Notícias O comércio varejista nacional teve alta de 0,7% em julho, após variação de 0,1% em junho. Com isso, a média móvel...',
      data_publicacao: '15/09/2023 09:00:00',
      produto_id: 9227,
      produtos: '9227|Pesquisa Mensal de Comércio|pesquisa-mensal-de-comercio|2075',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PMC_Thumb_Alerrandre-Barros.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PMC_Home_Alerrandre-Barros.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9227',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37908-volume-de-vendas-no-comercio-tem-alta-de-0-7-em-julho.html',
    },
    {
      id: 37894,
      tipo: 'Notícia',
      titulo: 'Em 2022, Sorriso (MT) manteve a liderança na produção agrícola',
      introducao: 'Com crescimento de 1,3%, valor de produção da soja chegou a R$ 345,4 bilhões em 2022 - Foto: Secom/MT Valor de produção e safra de grãos batem recorde em 2022 O valor de produção das principais culturas agrícolas do Brasil atingiu o recorde de R$ 830,1...',
      data_publicacao: '14/09/2023 10:00:00',
      produto_id: 0,
      produtos: '9117|Culturas temporárias e permanentes #PAM1|producao-agricola-municipal-culturas-temporarias-e-permanentes|2046;9119|Cereais, leguminosas e oleaginosas#PAM2|producao-agricola-municipal-cereais-leguminosas-e-oleaginosas|2046',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PAM_THUMB_Secom-MT.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PAM_HOME_Secom-MT.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9117, 9119',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37894-em-2022-sorriso-mt-manteve-a-lideranca-na-producao-agricola.html',
    },
    {
      id: 37899,
      tipo: 'Notícia',
      titulo: 'Com expansão de 0,5% em julho, serviços têm terceira alta consecutiva',
      introducao: 'O transporte de cargas (1,4%) exerceu a principal influência positiva sobre o resultado do setor de serviços no país - Foto: Helena Pontes/Agência IBGE Notícias Em julho, o volume de serviços prestados no país cresceu 0,5% frente ao mês anterior. É a...',
      data_publicacao: '14/09/2023 09:00:00',
      produto_id: 9229,
      produtos: '9229|Pesquisa Mensal de Serviços|pesquisa-mensal-de-servicos|2076',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PMS_THUMB_HelenaPontes.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PMS_HOME_HelenaPontes.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9229',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37899-com-expansao-de-0-5-em-julho-servicos-tem-terceira-alta-consecutiva.html',
    },
    {
      id: 37885,
      tipo: 'Notícia',
      titulo: 'Produção industrial recua em quatorze dos 15 locais pesquisados em julho frente a junho',
      introducao: 'O setor de equipamentos de informática, produtos eletrônicos e ópticos foi a maior influência no resultado da indústria no Amazonas - Foto: Tiago Ciccarini/SEJUSP Na passagem de junho para julho, a produção industrial brasileira recuou 0,6%, com quedas...',
      data_publicacao: '13/09/2023 09:00:00',
      produto_id: 9296,
      produtos: '9296|PIM-PF Regional#pimpf2|pesquisa-industrial-mensal-producao-fisica-regional|2209',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PIM-Reg_THUMB_Tiago-Ciccarini-SEJUSP.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PIM-Reg_HOME_Tiago-Ciccarini-SEJUSP.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9296',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37885-producao-industrial-recua-em-quatorze-dos-15-locais-pesquisados-em-julho-frente-a-junho.html',
    },
    {
      id: 37865,
      tipo: 'Notícia',
      titulo: ' Inflação fica em 0,23% em agosto, influenciada pelo aumento da energia elétrica',
      introducao: 'Aumento de 4,59% na energia elétrica residencial foi influenciado pelo fim da incorporação do Bônus de Itaipu, creditado nas faturas do mês anterior - Foto: Helena Pontes/Agência IBGE Notícias A inflação do mês de agosto foi de 0,23%, ficando 0,11 ponto...',
      data_publicacao: '12/09/2023 09:00:00',
      produto_id: 0,
      produtos: '9256|Índice Nacional de Preços ao Consumidor Amplo|indice-nacional-de-precos-ao-consumidor-amplo|2210;9258|Índice Nacional de Preços ao Consumidor|indice-nacional-de-precos-ao-consumidor|2077',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/IPCA_THUMB_Helena-Pontes_09.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/IPCA_HOME_Helena-Pontes_09-1.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9256, 9258',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37865-inflacao-fica-em-0-23-em-agosto-influenciada-pelo-aumento-da-energia-eletrica.html',
    },
    {
      id: 37863,
      tipo: 'Notícia',
      titulo: 'Preços da construção variam 0,18% em agosto ',
      introducao: 'Em agosto, preços da construção civil foram mais uma vez influenciados pela parcela dos profissionais - Foto: Helena Pontes/Agência IBGE Notícias O Índice Nacional da Construção Civil (Sinapi) apresentou variação de 0,18% em agosto. A taxa é 0,05 ponto...',
      data_publicacao: '12/09/2023 09:00:00',
      produto_id: 9270,
      produtos: '9270|Sistema Nacional de Pesquisa de Custos e Índices da Construção Civil|sistema-nacional-de-pesquisa-de-custos-e-indices-da-construcao-civil|2079',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/SINAPI_THUMB_Marcello-Casal-Jr-Agncia-Brasil.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/SINAPI_HOME_Marcello-Casal-Jr-Agncia-Brasil.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9270',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37863-precos-da-construcao-variam-0-18-em-agosto.html',
    },
    {
      id: 37832,
      tipo: 'Notícia',
      titulo: 'Estimativa de agosto prevê safra recorde de 313,3 milhões de toneladas para 2023',
      introducao: 'Com alta de 25,8%, para 150,3 milhões de toneladas, a produção da soja atinge novo recorde, assim como o trigo, o milho e o sorgo - Foto: Gilson Abreu/AEN-PR O Levantamento Sistemático da Produção Agrícola (LSPA), divulgado hoje (6) pelo IBGE, mostra que...',
      data_publicacao: '06/09/2023 09:00:00',
      produto_id: 9201,
      produtos: '9201|Levantamento Sistemático da Produção Agrícola|levantamento-sistematico-da-producao-agricola|2071',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/sojagilsonabreu-AEN-PR-THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/sojagilsonabreu-AEN-PR-HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9201',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37832-estimativa-de-agosto-preve-safra-recorde-de-313-3-milhoes-de-toneladas-para-2023.html',
    },
    {
      id: 37829,
      tipo: 'Notícia',
      titulo: 'Abate de bovinos cresce 12,6% no 2º trimestre, enquanto o de suínos cai pela primeira vez desde 2014 na comparação anual',
      introducao: 'Abate de bovinos chega a 8,36 milhões de cabeças no 2º trimestre de 2023, com aumentos tanto na comparação anual como na trimestral - Foto: Licia Rubinstein/Agência IBGE Notícias O abate de bovinos chegou a 8,36 milhões de cabeças no 2º trimestre de...',
      data_publicacao: '06/09/2023 09:00:00',
      produto_id: 0,
      produtos: '9216|Resultados completos#2ovos|pesquisa-trimestral-da-producao-de-ovos-de-galinha|2072;9209|Resultados completos#2leite|pesquisa-trimestral-do-leite|2219;9214|Resultados completos#2couro|pesquisa-trimestral-do-couro|2218;9203|Resultados completos#2abate|pesquisas-trimestrais-do-abate-de-animais|2220',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/Gado_031_LiciaR_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/Gado_031_LiciaR_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9216, 9209, 9214, 9203',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37829-abate-de-bovinos-cresce-12-6-no-2-trimestre-enquanto-o-de-suinos-cai-pela-primeira-vez-desde-2014-na-comparacao-anual.html',
    },
    {
      id: 37810,
      tipo: 'Notícia',
      titulo: 'Produção industrial tem perda de ritmo e recua 0,6% em julho',
      introducao: 'Indústria de veículos foi a principal influência para resultado negativo da indústria em julho - Foto: José Fernando Ogura/AEN-PR A produção industrial do país mostrou perda de ritmo e apresentou retração de 0,6% na passagem de junho para julho. O setor...',
      data_publicacao: '05/09/2023 09:00:00',
      produto_id: 9294,
      produtos: '9294|PIM-PF Brasil#pimpf1|pesquisa-industrial-mensal-producao-fisica-brasil|2209',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PIMBR-THUMB-JoseFernandoOgura_AEN_PR.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PIMBR-HOME-JoseFernandoOgura_AEN_PR.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9294',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37810-producao-industrial-tem-perda-de-ritmo-e-recua-0-6-em-julho.html',
    },
    {
      id: 37788,
      tipo: 'Notícia',
      titulo: 'IBGE abre inscrições para  120 vagas temporárias no Rio de Janeiro',
      introducao: 'LEGENDA - Foto: Licia Rubinstein/Agência IBGE Notícias O IBGE abriu hoje (4/09) as inscrições para o Processo Seletivo Simplificado que oferece 120 vagas temporárias para a função de Codificador Censitário. Todas as vagas são para trabalhar no município...',
      data_publicacao: '04/09/2023 09:00:00',
      produto_id: 22827,
      produtos: '22827|Censo 2022#3|censo-demografico-2022|2098',
      editorias: 'ibge;censo2020',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_09\\/PSS_THUMB_LiciaRubistein.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_09\\/PSS_HOME_LiciaRubistein.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '22827',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37788-ibge-abre-inscricoes-para-120-vagas-temporarias-no-rio-de-janeiro.html',
    },
    {
      id: 37775,
      tipo: 'Notícia',
      titulo: 'IBGE divulga a lista de vencedores do Prêmio Fotográfico do Censo 2022',
      introducao: 'O IBGE divulga hoje, 1º de setembro, o resultado final do Prêmio Fotográfico do Censo 2022. O concurso foi dividido em três categorias: paisagens urbanas, paisagens rurais e habitação. A premiação também considerou os votos do público, via internet. As...',
      data_publicacao: '01/09/2023 10:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge;censo2020',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/Concurso-fotogr_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/Concurso-fotogr_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37775-ibge-divulga-a-lista-de-vencedores-do-premio-fotografico-do-censo-2022.html',
    },
    {
      id: 37774,
      tipo: 'Notícia',
      titulo: 'PIB cresce 0,9% no segundo trimestre e fecha semestre com alta de 3,7%',
      introducao: 'A extração de petróleo, muito ligada à exportação, impactou a alta do PIB - Foto: Agência Petrobras Na passagem do primeiro para o segundo trimestre deste ano, o Produto Interno Bruto (PIB) cresceu 0,9%, oitavo resultado positivo consecutivo do indicador...',
      data_publicacao: '01/09/2023 09:00:00',
      produto_id: 9300,
      produtos: '9300|Sistema de Contas Nacionais Trimestrais|contas-nacionais-trimestrais|2087',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PIB-Tri_THUMB_AgenciaPetrobras.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PIB-Tri_HOME_AgenciaPetrobras.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9300',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37774-pib-cresce-0-9-no-segundo-trimestre-e-fecha-semestre-com-alta-de-3-7.html',
    },
    {
      id: 37745,
      tipo: 'Notícia',
      titulo: 'IBGE reforça compromisso com Agenda 2030 da ONU',
      introducao: 'Os Objetivos de Desenvolvimento Sustentável (ODS) integram a Agenda 2030 da Organização das Nações Unidas (ONU) - Foto: Licia Rubinstein/Agência IBGE Notícias Na última sexta-feira (25), membros de diferentes setores do IBGE se reuniram no Instituto...',
      data_publicacao: '31/08/2023 14:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/Evento-ODS_thumb_LiciaRubinstein.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/Evento-ODS_home_LiciaRubinstein.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37745-ibge-reforca-compromisso-com-agenda-2030-da-onu.html',
    },
    {
      id: 37753,
      tipo: 'Notícia',
      titulo: 'Ocupação no setor de serviços cresce 7,8% e chega ao recorde de 13,4 milhões',
      introducao: 'A ocupação em Serviços prestados principalmente às famílias caiu 8,5% ante 2019, por influência dos Serviços de alimentação, que perdeu 223,7 mil vagas - Foto: Helena Pontes/Agência IBGE Notícias A Pesquisa Anual de Serviços (PAS) 2021 mostrou um total...',
      data_publicacao: '31/08/2023 10:00:00',
      produto_id: 9028,
      produtos: '9028|Pesquisa Anual de Serviços #PAS1|pesquisa-anual-de-servicos|2008',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_08\\/PAS-THUMB-HelenaPontes.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_08\\/PAS-HOME-HelenaPontes.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9028',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37753-ocupacao-no-setor-de-servicos-cresce-7-8-e-chega-ao-recorde-de-13-4-milhoes.html',
    },
    {
      id: 37752,
      tipo: 'Notícia',
      titulo: 'Desemprego recua a 7,9% no trimestre encerrado em julho, menor taxa para o período desde 2014',
      introducao: 'População ocupada cresce em 1,3 milhão de pessoas no trimestre encerrado em julho - Foto - Acervo IBGE A taxa de desocupação foi 7,9% no trimestre encerrado em julho de 2023, mostrando recuo de 0,6 ponto percentual (p.p) em relação ao trimestre anterior,...',
      data_publicacao: '31/08/2023 09:00:00',
      produto_id: 9171,
      produtos: '9171|Divulgação mensal#pnadc1|pesquisa-nacional-por-amostra-de-domicilios-continua-mensal|2511',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_08\\/PNAD_THUMB_Acervo-IBGE.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_08\\/PNAD_HOME_Acervo-IBGE.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9171',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37752-desemprego-recua-a-7-9-no-trimestre-encerrado-em-julho-menor-taxa-para-o-periodo-desde-2014.html',
    },
    {
      id: 37739,
      tipo: 'Notícia',
      titulo: 'Preços na indústria caem 0,82% em julho, influenciados pelo setor de alimentos',
      introducao: 'O setor de maior influência foi o de alimentos, que caiu 1,36% e colaborou com -0,33 ponto percentual no resultado geral da indústria - Foto: José Fernando Ogura/AEN-PR Os preços da indústria caíram 0,82% em julho frente a junho, registrando o sexto mês...',
      data_publicacao: '30/08/2023 09:00:00',
      produto_id: 9282,
      produtos: '9282|Índice de Preços ao Produtor - Indústrias Extrativas e de Transformação|indice-de-precos-ao-produtor-industrias-extrativas-e-de-transformacao|2081',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_08\\/IPP_THUMB_Jos-Fernando-Ogura-AEN-PR.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_08\\/IPP_home_Jos-Fernando-Ogura-AEN-PR.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9282',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37739-precos-na-industria-caem-0-82-em-julho-influenciados-pelo-setor-de-alimentos.html',
    },
    {
      id: 37727,
      tipo: 'Notícia',
      titulo: 'IBGE publica estudo sobre excursão técnica nas montanhas fluminenses',
      introducao: 'Durante a excursão, os pesquisadores visitaram três pontos de montanha localizados na Serra dos Órgãos, no Rio de Janeiro - Foto: Acervo IBGE O IBGE divulgou hoje (29) uma publicação inédita com o roteiro e as discussões relativas a uma excursão técnica...',
      data_publicacao: '29/08/2023 10:00:00',
      produto_id: 28098,
      produtos: '28098|Sistema Brasileiro de Classificação de Relevo|sistema-brasileiro-de-classificacao-de-relevo|2997',
      editorias: 'geociencias',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/geociencias\\/2023_08\\/DGC_Excurses_THUMB_AcervoIBGE.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/geociencias\\/2023_08\\/DGC_Excurses_HOME_AcervoIBGE.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '28098',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37727-ibge-publica-estudo-sobre-excursao-tecnica-nas-montanhas-fluminenses.html',
    },
    {
      id: 37716,
      tipo: 'Notícia',
      titulo: 'Três novos índices mostram queda da pobreza e da vulnerabilidade entre 2008-2009 e 2017-2018',
      introducao: 'Estatística experimental do IBGE mede a pobreza com base em dimensões como moradia, transporte e lazer - Foto: Acervo IBGE O IBGE divulga pela primeira vez, como estatística experimental, a Evolução dos Indicadores não Monetários de Pobreza e Qualidade...',
      data_publicacao: '25/08/2023 10:00:00',
      produto_id: 24786,
      produtos: '24786|POF 2017-2018 #POF|pesquisa-de-orcamentos-familiares-2|2004',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_08\\/POF_THUMB_AcervoIBGE.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_08\\/POF_HOME_AcervoIBGE.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '24786',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37716-tres-novos-indices-mostram-queda-da-pobreza-e-da-vulnerabilidade-entre-2008-2009-e-2017-2018.html',
    },
    {
      id: 37715,
      tipo: 'Notícia',
      titulo: 'IPCA-15 fica em 0,28% em agosto, influenciado pela alta da energia elétrica',
      introducao: 'Fim do Bônus de Itaipu influenciou na alta da energia elétrica residencial (4,59%) - Foto: Helena Pontes/Agência IBGE Notícias A prévia da inflação ficou em 0,28% em agosto, 0,35 ponto percentual (p.p.) acima da taxa registrada em julho (-0,07%). Com...',
      data_publicacao: '25/08/2023 09:00:00',
      produto_id: 9260,
      produtos: '9260|Índice Nacional de Preços ao Consumidor Amplo 15|indice-nacional-de-precos-ao-consumidor-amplo-15|2213',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_08\\/IPCA15_THUMB_HelenaPontes.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_08\\/IPCA15_HOME_HelenaPontes.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9260',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37715-ipca-15-fica-em-0-28-em-agosto-influenciado-pela-alta-da-energia-eletrica.html',
    },
    {
      id: 37713,
      tipo: 'Notícia',
      titulo: 'IBGE participa de treinamento e teste cognitivo de questionário sobre educação inclusiva',
      introducao: 'Treinamento de pesquisadores e análise do questionário a ser aplicado nas entrevistas - Foto: Vinícius Britto IBGE/Agência IBGE Notícias O IBGE, em parceria com o UNICEF e o Grupo de Washington para Estatísticas sobre Pessoas com Deficiência (WG), está...',
      data_publicacao: '24/08/2023 10:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/treinamento_VinciusBritto-THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/treinamento_VinciusBritto-HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37713-ibge-participa-de-treinamento-e-teste-cognitivo-de-questionario-sobre-educacao-inclusiva.html',
    },
    {
      id: 37705,
      tipo: 'Notícia',
      titulo: 'Escola Virtual oferece curso on line gratuito de SIDRA',
      introducao: 'O curso é aberto a toda a sociedade, bastando que o participante tenha concluído o Ensino Médio - Foto: Arte sobre foto Freepik Os interessados em aprender a tabular dados estatísticos a partir do Sistema IBGE de Recuperação Automática (SIDRA) já podem...',
      data_publicacao: '23/08/2023 10:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/CursoSidra_THUMB_Freepick.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/CursoSidra_HOME_Freepick.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37705-escola-virtual-oferece-curso-on-line-gratuito-de-sidra.html',
    },
    {
      id: 37698,
      tipo: 'Notícia',
      titulo: 'IBGE realiza treinamento para as pesquisas MUNIC e ESTADIC 2023',
      introducao: 'Representantes das superintendências estaduais do IBGE estiveram reunidos para o treinamento das pesquisas MUNIC e ESTADIC - Foto: Adriana Saraiva/Agência IBGE Notícias Entre os dias 14 e 18 de agosto, representantes das superintendências estaduais do...',
      data_publicacao: '21/08/2023 17:30:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/Treinamento_MuncEstadic_Thumb_Adriana-Saraiva.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/Treinamento_MuncEstadic_Home_Adriana-Saraiva.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37698-ibge-realiza-treinamento-para-as-pesquisas-munic-e-estadic-2023.html',
    },
    {
      id: 37692,
      tipo: 'Notícia',
      titulo: 'Lula prestigia posse de Marcio Pochmann na Presidência do IBGE',
      introducao: 'O presidente Lula prestigiou a posse de Marcio Pochmann na presidência do IBGE- Foto - Washington Costa/MPO O presidente da República, Luiz Inácio Lula da Silva, prestigiou pessoalmente, nesta sexta-feira (18), a posse do novo presidente do IBGE, Marcio...',
      data_publicacao: '18/08/2023 17:40:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/Posse-Marcio-Pochman_THUMB_Washinton-Costa-MPO.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/Posse-Marcio-Pochman_HOME_Washinton-Costa-MPO.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37692-lula-prestigia-posse-de-marcio-pochmann-na-presidencia-do-ibge.html',
    },
    {
      id: 37675,
      tipo: 'Notícia',
      titulo: 'IBGE divulga estudo visando ampliar a categorização de espaços geográficos',
      introducao: 'Estudo diferencia espaços do território nacional em urbano, rural e natureza - Foto: Licia Rubinstein/Agência IBGE Notícias O IBGE divulgou nesta quarta-feira (16) o estudo “Proposta Metodológica para Classificação dos Espaços do Rural, do Urbano e da...',
      data_publicacao: '16/08/2023 10:00:00',
      produto_id: 15790,
      produtos: '15790|Classificação Rural e Urbana|classificacao-rural-e-urbana|2268',
      editorias: 'geociencias',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/geociencias\\/2023_08\\/DGC_THUMB_LiciaRubinstein-IBGE.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/geociencias\\/2023_08\\/DGC_HOME_LiciaRubinstein-IBGE.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '15790',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37675-ibge-divulga-estudo-visando-ampliar-a-categorizacao-de-espacos-geograficos.html',
    },
    {
      id: 37672,
      tipo: 'Notícia',
      titulo: 'IBGE abre inscrições para processos seletivos com 325 vagas na área de call center',
      introducao: 'Há 276 vagas para Agente de Pesquisas por Telefone (APT) e 49 vagas para Supervisor de Pesquisas por Telefone (SPT) - Foto: Marcio Costa/Agência IBGE Notícias Estão abertas a partir desta segunda-feira (14) as inscrições para dois processos seletivos...',
      data_publicacao: '15/08/2023 14:00:00',
      produto_id: 0,
      produtos: '',
      editorias: 'ibge',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/PSS-TELEFONIA_THUMB_MarcioCosta-IBGE.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_08\\/PSS-TELEFONIA_HOME_MarcioCosta-IBGE.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37672-ibge-abre-inscricoes-para-processos-seletivos-com-325-vagas-na-area-de-call-center.html',
    },
    {
      id: 37666,
      tipo: 'Notícia',
      titulo: 'Desocupação cai em oito unidades da federação no segundo trimestre',
      introducao: 'A taxa de desemprego recuou em quatro das cinco regiões do país - Foto: Jessica Candido/Agência IBGE Notícias No segundo trimestre, a queda da taxa de desocupação do país foi acompanhada por apenas oito unidades da federação, enquanto as demais...',
      data_publicacao: '15/08/2023 09:00:00',
      produto_id: 9173,
      produtos: '9173|Divulgação trimestral#pnadc2|pesquisa-nacional-por-amostra-de-domicilios-continua-trimestral|2511',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_08\\/PNAD-Tri_THUMB_JessicaCandido.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_08\\/PNAD-Tri_HOME_JessicaCandido.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9173',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37666-desocupacao-cai-em-oito-unidades-da-federacao-no-segundo-trimestre.html',
    },
    {
      id: 37621,
      tipo: 'Notícia',
      titulo: 'Em 2022, mulheres dedicaram 9,6 horas por semana a mais do que os homens aos afazeres domésticos ou ao cuidado de pessoas',
      introducao: 'Apenas quando moram sozinhos, homens realizam afazes domésticos em taxas semelhantes às das mulheres - Foto: Bel Corção/Brasil com S Em 2022, a população com 14 anos ou mais de idade dedicava, em média, 17 horas semanais aos afazeres domésticos e/ou...',
      data_publicacao: '11/08/2023 10:00:00',
      produto_id: 17270,
      produtos: '17270|Divulgação anual#pnadc3|pnad-continua|2511',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_08\\/PNAD_THUMB_BrasilcomS.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_08\\/PNAD_HOME_BrasilcomS.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '17270',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37621-em-2022-mulheres-dedicaram-9-6-horas-por-semana-a-mais-do-que-os-homens-aos-afazeres-domesticos-ou-ao-cuidado-de-pessoas.html',
    },
  ],
};
