/* eslint-disable max-lines */
/* eslint-disable sonarjs/no-duplicate-string */
/* eslint-disable max-len */

export const mockFetchRelease = {
  count: 3726,
  page: 1,
  totalPages: 125,
  nextPage: 2,
  previousPage: 0,
  showingFrom: 1,
  showingTo: 30,
  items: [
    {
      id: 37907,
      tipo: 'Release',
      titulo: 'Vendas no varejo sobem 0,7% em julho',
      introducao: 'Em julho de 2023, o volume de vendas do comércio varejista teve alta de 0,7% frente a junho, na série com ajuste sazonal. A média móvel trimestral foi de 0,1%. Frente a julho de 2022, houve alta de 2,4%, segunda alta consecutiva nessa comparação. O...',
      data_publicacao: '15/09/2023 09:00:00',
      produto_id: 9227,
      produtos: '9227|Pesquisa Mensal de Comércio|pesquisa-mensal-de-comercio|2075',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PMC_release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PMC_release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9227',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37907-vendas-no-varejo-sobem-0-7-em-julho.html',
    },
    {
      id: 37898,
      tipo: 'Release',
      titulo: 'Volume dos Serviços cresce 0,5% em julho',
      introducao: 'Em julho de 2023, o volume de serviços no Brasil cresceu 0,5% frente a junho, na série com ajuste sazonal. Foi o terceiro resultado positivo consecutivo do indicador, período em que acumulou ganho de 2,2%. O setor de serviços está 12,8% acima do nível de...',
      data_publicacao: '14/09/2023 09:00:00',
      produto_id: 9229,
      produtos: '9229|Pesquisa Mensal de Serviços|pesquisa-mensal-de-servicos|2076',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PMS_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PMS_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9229',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37898-volume-dos-servicos-cresce-0-5-em-julho.html',
    },
    {
      id: 37884,
      tipo: 'Release',
      titulo: 'Em julho, indústria recua em quatorze dos 15 locais pesquisados',
      introducao: 'Em julho de 2023, a produção industrial recuou 0,6% frente a junho, na série com ajuste sazonal, com taxas negativas em quatorze dos 15 locais pesquisados. As quedas mais intensas foram no Amazonas (-8,8%), Bahia (-6,0%) e Pará (-4,4%), embora as taxas...',
      data_publicacao: '13/09/2023 09:00:00',
      produto_id: 9296,
      produtos: '9296|PIM-PF Regional#pimpf2|pesquisa-industrial-mensal-producao-fisica-regional|2209',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PIM-PF-REGIONAL_Release.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PIM-PF-REGIONAL_Release.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9296',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37884-em-julho-industria-recua-em-quatorze-dos-15-locais-pesquisados.html',
    },
    {
      id: 37864,
      tipo: 'Release',
      titulo: 'IPCA foi de 0,23% em agosto',
      introducao: 'O Índice Nacional de Preços ao Consumidor Amplo (IPCA) foi de 0,23% em agosto, 0,11 ponto percentual (p.p.) acima da taxa de 0,12% registrada em julho. No ano, o IPCA acumula alta de 3,23% e, nos últimos 12 meses, de 4,61%. Em agosto de 2022, a variação...',
      data_publicacao: '12/09/2023 09:00:00',
      produto_id: 0,
      produtos: '9256|Índice Nacional de Preços ao Consumidor Amplo|indice-nacional-de-precos-ao-consumidor-amplo|2210;9258|Índice Nacional de Preços ao Consumidor|indice-nacional-de-precos-ao-consumidor|2077',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/IPCA_Release1.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/IPCA_Release1.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9256, 9258',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37864-ipca-foi-de-0-23-em-agosto.html',
    },
    {
      id: 37862,
      tipo: 'Release',
      titulo: 'Em agosto, Índice Nacional da Construção Civil é de 0,18%',
      introducao: 'O Índice Nacional da Construção Civil (SINAPI) foi de 0,18% em agosto, caindo 0,05 ponto percentual em relação ao índice de julho (0,23%). O acumulado nos últimos 12 meses foi para 3,11%, resultado abaixo dos 3,52% registrados nos 12 meses imediatamente...',
      data_publicacao: '12/09/2023 09:00:00',
      produto_id: 9270,
      produtos: '9270|Sistema Nacional de Pesquisa de Custos e Índices da Construção Civil|sistema-nacional-de-pesquisa-de-custos-e-indices-da-construcao-civil|2079',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/SINAPI_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/SINAPI_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9270',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37862-em-agosto-indice-nacional-da-construcao-civil-e-de-0-18.html',
    },
    {
      id: 37830,
      tipo: 'Release',
      titulo: 'Em agosto, IBGE prevê safra recorde de 313,3 milhões de toneladas para 2023',
      introducao: 'A estimativa de agosto para a produção de cereais, leguminosas e oleaginosas de 2023 é de 313,3 milhões de toneladas, 19,0% maior (ou mais 50,1 milhões de toneladas) que a de 2022 (263,2 milhões de toneladas) e 1,4% acima da estimativa de julho. A área a...',
      data_publicacao: '06/09/2023 09:00:00',
      produto_id: 9201,
      produtos: '9201|Levantamento Sistemático da Produção Agrícola|levantamento-sistematico-da-producao-agricola|2071',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/LSPA_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/LSPA_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9201',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37830-em-agosto-ibge-preve-safra-recorde-de-313-3-milhoes-de-toneladas-para-2023.html',
    },
    {
      id: 37828,
      tipo: 'Release',
      titulo: 'Cresce o abate de bovinos e frangos e cai o de suínos no 2º tri de 2023',
      introducao: 'No 2º trimestre de 2023, o abate de frangos subiu 4,7%, o de bovinos aumentou 12,6% e o de suínos caiu 1,0% ante o mesmo período de 2022. Frente ao 1º trimestre de 2023, o abate de frangos caiu 3,2%, o de bovinos cresceu 13,4% e o de suínos recuou 0,6%....',
      data_publicacao: '06/09/2023 09:00:00',
      produto_id: 0,
      produtos: '9216|Resultados completos#2ovos|pesquisa-trimestral-da-producao-de-ovos-de-galinha|2072;9209|Resultados completos#2leite|pesquisa-trimestral-do-leite|2219;9214|Resultados completos#2couro|pesquisa-trimestral-do-couro|2218;9203|Resultados completos#2abate|pesquisas-trimestrais-do-abate-de-animais|2220',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/TriPecuaria_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/TriPecuaria_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9216, 9209, 9214, 9203',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37828-cresce-o-abate-de-bovinos-e-frangos-e-cai-o-de-suinos-no-2-tri-de-2023.html',
    },
    {
      id: 37809,
      tipo: 'Release',
      titulo: 'Produção industrial recua 0,6% em julho',
      introducao: 'Em julho de 2023, a produção industrial nacional recuou 0,6% frente a junho, na série com ajuste sazonal. Em relação a julho de 2022, a queda foi de 1,1%. No ano, a indústria acumula taxa negativa (-0,4%) frente a igual período de 2022, e variação nula...',
      data_publicacao: '05/09/2023 09:00:00',
      produto_id: 9294,
      produtos: '9294|PIM-PF Brasil#pimpf1|pesquisa-industrial-mensal-producao-fisica-brasil|2209',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PIM-PF-BR_Release1.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PIM-PF-BR_Release1.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9294',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37809-producao-industrial-recua-0-6-em-julho.html',
    },
    {
      id: 37773,
      tipo: 'Release',
      titulo: 'PIB cresce 0,9% no 2º trimestre de 2023',
      introducao: 'O Produto Interno Bruto (PIB) cresceu 0,9% no segundo trimestre de 2023, ante o trimestre anterior, na série com ajuste sazonal. Frente ao mesmo trimestre de 2022, o PIB cresceu 3,4%. No acumulado dos quatro trimestres terminados em junho de 2023, o PIB...',
      data_publicacao: '01/09/2023 09:00:00',
      produto_id: 9300,
      produtos: '9300|Sistema de Contas Nacionais Trimestrais|contas-nacionais-trimestrais|2087',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PIB_release_nac_tri.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PIB_release_nac_tri.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9300',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37773-pib-cresce-0-9-no-2-trimestre-de-2023.html',
    },
    {
      id: 37758,
      tipo: 'Release',
      titulo: 'IBGE divulga relação da população dos municípios',
      introducao: 'O IBGE publicou no Diário Oficial da União desta quinta-feira (31), a relação das populações dos municípios do país, segundo o Censo 2022, com atualizações dos seus limites territoriais. Veja, aqui. Essa publicação obedece ao art. 102 da Lei n° 8.443/92...',
      data_publicacao: '31/08/2023 09:00:00',
      produto_id: 37734,
      produtos: '37734|Relação da População dos Municípios para publicação no DOU em 2023|relacao-da-populacao-dos-municipios-para-publicacao-no-dou|3072',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/Relao_da_Populao_dos_Municpios_release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/Relao_da_Populao_dos_Municpios_release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '37734',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37758-ibge-divulga-relacao-da-populacao-dos-municipios.html',
    },
    {
      id: 37750,
      tipo: 'Release',
      titulo: 'PNAD Contínua: taxa de desocupação é de 7,9% e  taxa de subutilização é de 17,8% no trimestre encerrado em julho',
      introducao: 'A taxa de desocupação (7,9%) do trimestre de maio a julho de 2023 recuou 0,6 ponto percentual (p.p.) frente ao trimestre de fevereiro a abril de 2023 (8,5%) e caiu 1,2 p.p. ante o mesmo trimestre móvel de 2022 (9,1%). Essa foi a menor taxa de desocupação...',
      data_publicacao: '31/08/2023 09:00:00',
      produto_id: 9173,
      produtos: '9173|Divulgação trimestral#pnadc2|pesquisa-nacional-por-amostra-de-domicilios-continua-trimestral|2511',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PNAD_Tri_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PNAD_Tri_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9173',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37750-pnad-continua-taxa-de-desocupacao-e-de-7-9-e-taxa-de-subutilizacao-e-de-17-8-no-trimestre-encerrado-em-julho.html',
    },
    {
      id: 37737,
      tipo: 'Release',
      titulo: 'Índice de Preços ao Produtor (IPP) é de -0,82% em julho',
      introducao: 'Em julho de 2023, os preços da indústria variaram -0,82% frente a junho, sexta queda consecutiva. Nessa comparação, 16 das 24 atividades industriais tiveram queda de preços. O acumulado no ano foi de -7,23%, o menor para um mês de julho desde o início da...',
      data_publicacao: '30/08/2023 09:00:00',
      produto_id: 9282,
      produtos: '9282|Índice de Preços ao Produtor - Indústrias Extrativas e de Transformação|indice-de-precos-ao-produtor-industrias-extrativas-e-de-transformacao|2081',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/IPP_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/IPP_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9282',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37737-indice-de-precos-ao-produtor-ipp-e-de-0-82-em-julho.html',
    },
    {
      id: 37714,
      tipo: 'Release',
      titulo: 'IPCA-15 foi de 0,28% em agosto',
      introducao: 'O Índice Nacional de Preços ao Consumidor Amplo 15 (IPCA-15) foi de 0,28% em agosto, 0,35 ponto percentual (p.p.) acima da taxa de julho (-0,07%). No ano, o IPCA-15 acumula alta de 3,38% e, em 12 meses, de 4,24%, acima dos 3,19% registrados nos 12 meses...',
      data_publicacao: '25/08/2023 09:00:00',
      produto_id: 9260,
      produtos: '9260|Índice Nacional de Preços ao Consumidor Amplo 15|indice-nacional-de-precos-ao-consumidor-amplo-15|2213',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/IPCA15_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/IPCA15_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9260',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37714-ipca-15-foi-de-0-28-em-agosto.html',
    },
    {
      id: 37664,
      tipo: 'Release',
      titulo: 'PNAD Contínua Trimestral: desocupação recua  em oito das 27 UFs no segundo trimestre de 2023',
      introducao: 'A taxa de desocupação do país no segundo trimestre de 2023 foi de 8,0%, caindo 0,8 ponto percentual (p.p.) ante o primeiro trimestre deste ano (8,8%) e 1,3 p.p. frente ao mesmo trimestre de 2022 (9,3%). Em relação ao trimestre anterior, a taxa de...',
      data_publicacao: '15/08/2023 09:00:00',
      produto_id: 9173,
      produtos: '9173|Divulgação trimestral#pnadc2|pesquisa-nacional-por-amostra-de-domicilios-continua-trimestral|2511',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PNAD_Tri_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PNAD_Tri_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9173',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37664-pnad-continua-trimestral-desocupacao-recua-em-oito-das-27-ufs-no-segundo-trimestre-de-2023.html',
    },
    {
      id: 37625,
      tipo: 'Release',
      titulo: 'IPCA foi de 0,12% em julho',
      introducao: 'O Índice Nacional de Preços ao Consumidor Amplo (IPCA) foi de 0,12% em julho, 0,20 ponto percentual (p.p.) acima da taxa de junho (-0,08%). No ano, o IPCA acumula alta de 2,99% e, nos últimos 12 meses, de 3,99%, acima dos 3,16% observados nos 12 meses...',
      data_publicacao: '11/08/2023 09:00:00',
      produto_id: 0,
      produtos: '9256|Índice Nacional de Preços ao Consumidor Amplo|indice-nacional-de-precos-ao-consumidor-amplo|2210;9258|Índice Nacional de Preços ao Consumidor|indice-nacional-de-precos-ao-consumidor|2077',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/IPCA_Release1.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/IPCA_Release1.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9256, 9258',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37625-ipca-foi-de-0-12-em-julho.html',
    },
    {
      id: 37620,
      tipo: 'Release',
      titulo: 'Em julho, Índice Nacional da Construção Civil é de 0,23%',
      introducao: 'O Índice Nacional da Construção Civil (Sinapi) foi de 0,23% em julho, caindo 0,16 ponto percentual em relação ao índice de junho (0,39%). O acumulado nos últimos 12 meses foi para 3,52%, resultado abaixo dos 4,82% registrados nos 12 meses imediatamente...',
      data_publicacao: '11/08/2023 09:00:00',
      produto_id: 9270,
      produtos: '9270|Sistema Nacional de Pesquisa de Custos e Índices da Construção Civil|sistema-nacional-de-pesquisa-de-custos-e-indices-da-construcao-civil|2079',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/SINAPI_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/SINAPI_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9270',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37620-em-julho-indice-nacional-da-construcao-civil-e-de-0-23.html',
    },
    {
      id: 37596,
      tipo: 'Release',
      titulo: 'Trimestrais da pecuária - primeiros resultados: abate de bovinos e frangos cresce no 2º trimestre de 2023',
      introducao: 'Os primeiros resultados da produção animal no 2º trimestre de 2023 apontam que, ante o mesmo período de 2022, o abate de bovinos cresceu 11,0%, o de frangos aumentou 4,7% e o de suínos caiu 1,6%. Frente ao 1º trimestre de 2023, o abate de bovinos teve...',
      data_publicacao: '10/08/2023 09:00:00',
      produto_id: 0,
      produtos: '21120|Primeiros resultados#1ovos|primeiros-resultados-1ovos|2072;21121|Primeiros resultados#1leite|primeiros-resultadios-2leite|2219;21122|Primeiros resultados#1couro|primeiros-resultados-1couro|2218;21119|Primeiros resultados#1abate|primeiros-resultados-2abate|2220',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/TriPecuaria_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/TriPecuaria_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '21120, 21121, 21122, 21119',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37596-trimestrais-da-pecuaria-primeiros-resultados-abate-de-bovinos-e-frangos-cresce-no-2-trimestre-de-2023.html',
    },
    {
      id: 37607,
      tipo: 'Release',
      titulo: 'Em julho, IBGE prevê safra de 308,9 milhões de toneladas para 2023',
      introducao: 'A estimativa de julho para a produção de cereais, leguminosas e oleaginosas de 2023 é de 308,9 milhões de toneladas, 17,4% maior (ou mais 45,7 milhões de toneladas) que a obtida em 2022 (263,2 milhões de toneladas) e 0,5% acima da estimativa de junho. A...',
      data_publicacao: '10/08/2023 09:00:00',
      produto_id: 9201,
      produtos: '9201|Levantamento Sistemático da Produção Agrícola|levantamento-sistematico-da-producao-agricola|2071',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/LSPA_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/LSPA_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9201',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37607-em-julho-ibge-preve-safra-de-308-9-milhoes-de-toneladas-para-2023.html',
    },
    {
      id: 37589,
      tipo: 'Release',
      titulo: 'Volume dos Serviços varia 0,2% em junho',
      introducao: 'Em junho de 2023, o volume de serviços no Brasil variou 0,2% frente a maio, na série com ajuste sazonal, após ter avançado 1,4% em maio. Dessa forma, o setor se encontra 12,1% acima do nível de fevereiro de 2020 (pré-pandemia) e 1,5% abaixo de dezembro...',
      data_publicacao: '10/08/2023 09:00:00',
      produto_id: 9229,
      produtos: '9229|Pesquisa Mensal de Serviços|pesquisa-mensal-de-servicos|2076',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PMS_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PMS_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9229',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37589-volume-dos-servicos-varia-0-2-em-junho.html',
    },
    {
      id: 37579,
      tipo: 'Release',
      titulo: 'Vendas no varejo ficam estáveis (0,0%) em junho',
      introducao: 'Em junho de 2023, o volume de vendas do comércio varejista mostrou estabilidade (0,0%) frente a maio, na série com ajuste sazonal. A média móvel trimestral para o varejo foi de -0,3% no trimestre encerrado em junho. Na série sem ajuste sazonal, o...',
      data_publicacao: '09/08/2023 09:00:00',
      produto_id: 9227,
      produtos: '9227|Pesquisa Mensal de Comércio|pesquisa-mensal-de-comercio|2075',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PMC_release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PMC_release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9227',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37579-vendas-no-varejo-ficam-estaveis-0-0-em-junho.html',
    },
    {
      id: 37571,
      tipo: 'Release',
      titulo: 'Em junho, indústria cresce em seis dos 15 locais pesquisados',
      introducao: 'Em junho de 2023, a produção industrial nacional avançou 0,1% frente a maio, na série com ajuste sazonal, e seis dos 15 locais pesquisados apresentaram taxas positivas. As maiores altas foram no Espírito Santo (4,6%), Rio de Janeiro (3,2%) e em Santa...',
      data_publicacao: '08/08/2023 09:00:00',
      produto_id: 9296,
      produtos: '9296|PIM-PF Regional#pimpf2|pesquisa-industrial-mensal-producao-fisica-regional|2209',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PIM-PF-REGIONAL_Release.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PIM-PF-REGIONAL_Release.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9296',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37571-em-junho-industria-cresce-em-seis-dos-15-locais-pesquisados.html',
    },
    {
      id: 37521,
      tipo: 'Release',
      titulo: 'Produção industrial varia 0,1% em junho',
      introducao: 'Em junho de 2023, a produção industrial nacional variou 0,1% frente a maio, na série com ajuste sazonal. Em relação a junho de 2022, na série sem ajuste sazonal, houve variação de 0,3%, segunda taxa positiva consecutiva, mas menos intensa do que a...',
      data_publicacao: '01/08/2023 09:00:00',
      produto_id: 9294,
      produtos: '9294|PIM-PF Brasil#pimpf1|pesquisa-industrial-mensal-producao-fisica-brasil|2209',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PIM-PF-BR_Release1.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PIM-PF-BR_Release1.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9294',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37521-producao-industrial-varia-0-1-em-junho.html',
    },
    {
      id: 37481,
      tipo: 'Release',
      titulo: 'PNAD Contínua: taxa de desocupação é de 8,0% e taxa de subutilização é de 17,8% no trimestre encerrado em junho',
      introducao: 'A taxa de desocupação (8,0%) do trimestre de abril a junho de 2023 recuou 0,8 ponto percentual (p.p.) em relação ao trimestre encerrado em março de 2023 (8,8%) e caiu 1,3 p.p. ante o mesmo período do ano anterior (9,3%). Foi a menor taxa para um...',
      data_publicacao: '28/07/2023 09:00:00',
      produto_id: 9171,
      produtos: '9171|Divulgação mensal#pnadc1|pesquisa-nacional-por-amostra-de-domicilios-continua-mensal|2511',
      editorias: 'sociais',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PNAD_C_Mensal_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PNAD_C_Mensal_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9171',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37481-pnad-continua-taxa-de-desocupacao-e-de-8-0-e-taxa-de-subutilizacao-e-de-17-8-no-trimestre-encerrado-em-junho.html',
    },
    {
      id: 37467,
      tipo: 'Release',
      titulo: 'Índice de Preços ao Produtor (IPP) é de -2,72% em junho',
      introducao: 'Em junho de 2023, os preços da indústria variaram -2,72% frente a maio, quinto resultado negativo consecutivo. Nessa comparação, 19 das 24 atividades industriais tiveram queda de preços. O acumulado no ano foi de -6,46%, o menor para um mês de junho...',
      data_publicacao: '27/07/2023 09:00:00',
      produto_id: 9282,
      produtos: '9282|Índice de Preços ao Produtor - Indústrias Extrativas e de Transformação|indice-de-precos-ao-produtor-industrias-extrativas-e-de-transformacao|2081',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/IPP_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/IPP_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9282',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37467-indice-de-precos-ao-produtor-ipp-e-de-2-72-em-junho.html',
    },
    {
      id: 37442,
      tipo: 'Release',
      titulo: 'IPCA-15 foi de -0,07% em julho',
      introducao: 'O Índice Nacional de Preços ao Consumidor Amplo 15 (IPCA-15) foi de -0,07% em julho, 0,11 ponto percentual (p.p.) abaixo da taxa de junho (0,04%). No ano, o IPCA-15 acumula alta de 3,09% e, em 12 meses, de 3,19%, abaixo dos 3,40% registrados nos 12 meses...',
      data_publicacao: '25/07/2023 09:00:00',
      produto_id: 9260,
      produtos: '9260|Índice Nacional de Preços ao Consumidor Amplo 15|indice-nacional-de-precos-ao-consumidor-amplo-15|2213',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/IPCA15_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/IPCA15_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9260',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37442-ipca-15-foi-de-0-07-em-julho.html',
    },
    {
      id: 37392,
      tipo: 'Release',
      titulo: 'Em maio, vendas no varejo caem 1,0%',
      introducao: 'Em maio de 2023, o volume de vendas do comércio varejista recuou 1,0%, frente a abril, na série com ajuste sazonal. A média móvel trimestral foi de -0,1%. Na série sem ajuste sazonal, o comércio varejista também caiu 1,0% frente a maio de 2022, com a...',
      data_publicacao: '14/07/2023 09:00:00',
      produto_id: 9227,
      produtos: '9227|Pesquisa Mensal de Comércio|pesquisa-mensal-de-comercio|2075',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PMC_release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PMC_release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9227',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37392-em-maio-vendas-no-varejo-caem-1-0.html',
    },
    {
      id: 37372,
      tipo: 'Release',
      titulo: 'Em junho, IBGE prevê safra de 307,3 milhões de toneladas para 2023',
      introducao: 'A estimativa de junho para a produção de cereais, leguminosas e oleaginosas de 2023 é de 307,3 milhões de toneladas, 16,8% maior (ou mais 44,2 milhões de toneladas) que a obtida em 2022 (263,2 milhões de toneladas) e 0,6% acima da estimativa de maio. A...',
      data_publicacao: '13/07/2023 09:00:00',
      produto_id: 9201,
      produtos: '9201|Levantamento Sistemático da Produção Agrícola|levantamento-sistematico-da-producao-agricola|2071',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/LSPA_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/LSPA_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9201',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37372-em-junho-ibge-preve-safra-de-307-3-milhoes-de-toneladas-para-2023.html',
    },
    {
      id: 37371,
      tipo: 'Release',
      titulo: 'Em maio, indústria cresce em dez dos 15 locais pesquisados',
      introducao: 'Em maio de 2023, a produção industrial nacional avançou 0,3% frente a abril, na série com ajuste sazonal, e dez dos 15 locais pesquisados apresentaram taxas positivas. As maiores altas foram no Amazonas (12,8%), Pernambuco (5,6%) e Paraná (5,3%). Já...',
      data_publicacao: '13/07/2023 09:00:00',
      produto_id: 9296,
      produtos: '9296|PIM-PF Regional#pimpf2|pesquisa-industrial-mensal-producao-fisica-regional|2209',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PIM-PF-REGIONAL_Release.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PIM-PF-REGIONAL_Release.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9296',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37371-em-maio-industria-cresce-em-dez-dos-15-locais-pesquisados.html',
    },
    {
      id: 37361,
      tipo: 'Release',
      titulo: 'Volume dos Serviços cresce 0,9% em maio',
      introducao: 'Em maio de 2023, o volume de serviços no Brasil se expandiu 0,9% frente a abril, na série com ajuste sazonal, após ter recuado 1,5% no mês anterior. Dessa forma, o setor se encontra 11,5% acima do nível de fevereiro de 2020 (pré-pandemia) e 2,0% abaixo...',
      data_publicacao: '12/07/2023 09:00:00',
      produto_id: 9229,
      produtos: '9229|Pesquisa Mensal de Serviços|pesquisa-mensal-de-servicos|2076',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PMS_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PMS_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9229',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37361-volume-dos-servicos-cresce-0-9-em-maio.html',
    },
    {
      id: 37337,
      tipo: 'Release',
      titulo: 'IPCA foi de -0,08% em junho',
      introducao: 'O Índice Nacional de Preços ao Consumidor Amplo (IPCA) foi de -0,08% em junho, 0,31 ponto percentual (p.p.) abaixo da taxa de maio (0,23%). Essa foi a menor variação para o mês de junho desde 2017, quando o índice foi de -0,23%. No ano, o IPCA acumula...',
      data_publicacao: '11/07/2023 09:00:00',
      produto_id: 0,
      produtos: '9256|Índice Nacional de Preços ao Consumidor Amplo|indice-nacional-de-precos-ao-consumidor-amplo|2210;9258|Índice Nacional de Preços ao Consumidor|indice-nacional-de-precos-ao-consumidor|2077',
      editorias: 'economicas',
      imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/IPCA_Release1.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/IPCA_Release1.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
      produtos_relacionados: '9256, 9258',
      destaque: true,
      link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37337-ipca-foi-de-0-08-em-junho.html',
    },
  ],
};
